---

language: python
services: docker

env:
  matrix:
  - MOLECULE_DISTRO: centos7
  - MOLECULE_DISTRO: ubuntu1804
  - MOLECULE_DISTRO: debian9

install:
- pip install -r requirements.txt

# We use the anticipated Ansible Galaxy role name for the project directory,
# not the git repo name. So, before doing anything, move the checkout...

before_script:
- cd ../
- mv cylc_core alanbchristie.cylc_core
- cd alanbchristie.cylc_core

script:
- molecule test
