---

language: python
services: docker

env:
  global:
  - ROLE_NAME: cylc-core
  matrix:
  - MOLECULE_DISTRO: centos7
  - MOLECULE_DISTRO: ubuntu1804
  - MOLECULE_DISTRO: debian9

install:
- pip install -r requirements.txt

# We use the anticipated Ansible Galaxy role name for the project directory,
# not the git repo name. So, before doing anything, move the checkout...

before_script:
- cd ../
- mv ansible-role-$ROLE_NAME alanbchristie.$ROLE_NAME
- cd alanbchristie.$ROLE_NAME

script:
- molecule test
