---

dist: xenial
language: python
services: docker

python:
- 3.7

env:
  matrix:
  # Core platforms
  - MOLECULE_DISTRO: centos7
  - MOLECULE_DISTRO: ubuntu1804
  - MOLECULE_DISTRO: debian9

  # Test the visualisation installation
  - MOLECULE_DISTRO: centos7
    MOLECULE_PLAYBOOK: playbook-visualisation.yml

install:
- pip install -r requirements.txt

# We use the anticipated Ansible Galaxy role name for the project directory,
# not the git repo name. So, before doing anything, move the checkout...

before_script:
- cd ../
- mv cylc alanbchristie.cylc
- cd alanbchristie.cylc

script:
- molecule test
