---

# Entry sanity check...

- name: Initial checks
  assert:
    that:
    - cylc_version|length > 0
    - cylc_version is version('7.0', '>=')
    - cylc_version is version('8.0', '<')

# Install dependent packages and modules...

- name: Set anticipated home
  set_fact:
    cylc_home: /opt/cylc-flow-{{ cylc_version }}

- name: Check anticipated home
  stat:
    path: "{{ cylc_home }}"
  register: ch

# Install only if it appears the installation directory
# for the named release does not exist...

- name: Install Cylc
  import_tasks: install.yml
  when: not ch.stat.exists
