---

# Creates a Python 3 virtual environment
# (for the supplied user)

- name: Check variables
  assert:
    that:
    - environment_user_name is defined
    - environment_name is defined

# Stuff

- name: Defeat remote_tmp warning
  file:
    path: /root/.ansible/tmp
    state: directory
    owner: root
    group: root
  become: yes

- name: Install yum utils
  yum:
    name:
    - yum-utils
    - "@Development tools"
    lock_timeout: 180
  become: yes

- name: Install extra packages
  package:
    name:
    - https://centos7.iuscommunity.org/ius-release.rpm
    - python36
    lock_timeout: 180
  become: yes

# Where's the user's home?

- name: Extract user's HOME
  getent:
    database: passwd
    key: "{{ environment_user_name }}"
    split: ":"

- name: Set user's HOME fact
  set_fact:
    user_home: "{{ getent_passwd[environment_user_name][4] }}"

# Python 3

- name: Create Python 3 virtual environment directory
  file:
    path: "{{ user_home }}/environments"
    state: directory
    owner: "{{ environment_user_name }}"
  become: yes
  become_user: "{{ environment_user_name }}"

- name: Check Python 3 virtual environment directory
  stat:
    path: "{{ user_home }}/environments/{{ environment_name }}"
  register: venv_dir
  become: yes
  become_user: "{{ environment_user_name }}"

- name: Create Python 3 virtual environment
  command: python3.6 -m venv {{ environment_name }}
  args:
    chdir: "{{ user_home }}/environments"
  when: not venv_dir.stat.exists
  become: yes
  become_user: "{{ environment_user_name }}"

- name: Add environment to bashrc
  lineinfile:
    path: "{{ user_home }}/.bashrc"
    regex: source ~/environments/{{ environment_name }}/bin/activate
    line: source ~/environments/{{ environment_name }}/bin/activate
  become: yes
  become_user: "{{ environment_user_name }}"
