---

- name: Install packages
  package:
    name:
    - at
    - git
  notify: Restart atd

- name: Create cylc user
  user:
    name: cylc
    groups: wheel
  become: yes

- name: Allow password-less sudo
  copy:
    content: "cylc ALL=(ALL) NOPASSWD: ALL"
    dest: /etc/sudoers.d/cylc
    mode: 0440
  become: yes

- name: Download cylc
  git:
    repo: https://github.com/cylc/cylc-flow.git
    dest: /opt/cylc
    version: "{{ cylc_version }}"
  become: yes

- name: Add cylc to system-wide profile
  template:
    src: cylc-profile.sh.j2
    dest: /etc/profile.d/cylc-profile.sh
    owner: root
    group: root
    mode: 0644
  vars:
    cylc_bin_dir: /opt/cylc/bin
  become: yes

- name: Get cylc version
  command: cylc version
  register: cylc_v
  changed_when: false

- name: Assert cylc version
  assert:
    that: cylc_v.stdout == '{{ cylc_version }}'
